import type { TelemetryPacket } from "@raceiq/shared/telemetry/types";
import { registerPMRIdentity } from "@raceiq/game-pmr-metadata/index";
import { decodePMRFrame } from "./frame";
const clamp = (v: number, min: number, max: number) => Math.max(min, Math.min(max, v));
const input255 = (v: number) => Math.round(clamp(v, 0, 1) * 255);
const canonicalGear = (v: number) => (v < 0 ? 0 : v === 0 ? 11 : v);
function identityOrdinal(name: string): number {
  let hash = 2166136261;
  for (const byte of Buffer.from(name, "utf8")) hash = Math.imul(hash ^ byte, 16777619);
  return (hash >>> 0) & 0x7fffffff || 1;
}
export function normalizePMRFrame(raw: Buffer): TelemetryPacket | null {
  const frame = decodePMRFrame(raw);
  if (!frame) return null;
  const { race, state, telemetry } = frame;
  if (race.state !== 1 || state.dq || state.sessionFinished || !state.vehicleName.trim()) return null;
  const carName = state.vehicleName.trim();
  const trackName = [race.track.trim(), race.layout.trim()].filter(Boolean).join(" - ");
  const carOrdinal = identityOrdinal(carName);
  const trackOrdinal = identityOrdinal(trackName);
  registerPMRIdentity(carOrdinal, carName, trackOrdinal, trackName, race.layoutLength);
  return {
    gameId: "pmr",
    sessionUID: JSON.stringify([frame.epoch, race.session, race.gameMode, carName, trackName]),
    pmr: {
      protocolVersion: state.version,
      ...(state.version === 2
        ? {
            lastLapTime: state.lastLapTime,
            lastSectorTimes: state.lastSectorTimes,
            lapValid: state.lapValid,
            inPitLane: state.inPitLane,
            tyreCompoundFront: state.tyreCompoundFront,
            tyreCompoundRear: state.tyreCompoundRear,
          }
        : {}),
      carName,
      trackName,
      trackLengthM: race.layoutLength,
      lapFraction: state.lapProgress,
      sessionType: race.session,
      currentSector: state.currentSector,
      currentSectorTimes: state.currentSectorTimes,
      bestSectorTimes: state.bestSectorTimes,
      inPits: state.inPits,
      disqualified: state.dq,
      brakeBias: telemetry.setup.brakeBias,
      absLevel: telemetry.setup.absLevel,
      tcsLevel: telemetry.setup.tcsLevel,
    },
    TireCarcassAverageTempFL: telemetry.wheels[0]!.carcassTemp,
    TireSurfaceTempInnerFL: telemetry.wheels[0]!.treadTemp[0]!,
    TireSurfaceTempMiddleFL: telemetry.wheels[0]!.treadTemp[1]!,
    TireSurfaceTempOuterFL: telemetry.wheels[0]!.treadTemp[2]!,
    TireCarcassAverageTempFR: telemetry.wheels[1]!.carcassTemp,
    TireSurfaceTempInnerFR: telemetry.wheels[1]!.treadTemp[2]!,
    TireSurfaceTempMiddleFR: telemetry.wheels[1]!.treadTemp[1]!,
    TireSurfaceTempOuterFR: telemetry.wheels[1]!.treadTemp[0]!,
    TireCarcassAverageTempRL: telemetry.wheels[2]!.carcassTemp,
    TireSurfaceTempInnerRL: telemetry.wheels[2]!.treadTemp[0]!,
    TireSurfaceTempMiddleRL: telemetry.wheels[2]!.treadTemp[1]!,
    TireSurfaceTempOuterRL: telemetry.wheels[2]!.treadTemp[2]!,
    TireCarcassAverageTempRR: telemetry.wheels[3]!.carcassTemp,
    TireSurfaceTempInnerRR: telemetry.wheels[3]!.treadTemp[2]!,
    TireSurfaceTempMiddleRR: telemetry.wheels[3]!.treadTemp[1]!,
    TireSurfaceTempOuterRR: telemetry.wheels[3]!.treadTemp[0]!,
    FuelCapacity: telemetry.constant.fuelCapacity,
    AirTemp: race.ambientTemperature,
    TrackTemp: race.trackTemperature,
    RainPercent: 0,
    BrakeTempFrontLeft: telemetry.wheels[0]!.brakeTemp,
    TirePressureFrontLeft: telemetry.wheels[0]!.pressure / 6894.757293,
    BrakeTempFrontRight: telemetry.wheels[1]!.brakeTemp,
    TirePressureFrontRight: telemetry.wheels[1]!.pressure / 6894.757293,
    BrakeTempRearLeft: telemetry.wheels[2]!.brakeTemp,
    TirePressureRearLeft: telemetry.wheels[2]!.pressure / 6894.757293,
    BrakeTempRearRight: telemetry.wheels[3]!.brakeTemp,
    TirePressureRearRight: telemetry.wheels[3]!.pressure / 6894.757293,
    IsRaceOn: race.state === 1 && !state.sessionFinished && !state.dq ? 1 : 0,
    TimestampMS: frame.timestampMs,
    EngineMaxRpm: telemetry.constant.engineMaxRPM,
    EngineIdleRpm: 0,
    CurrentEngineRpm: telemetry.drivetrain.engineRPM,
    AccelerationX: telemetry.chassis.accelerationLS[0]!,
    AccelerationY: telemetry.chassis.accelerationLS[1]!,
    AccelerationZ: telemetry.chassis.accelerationLS[2]!,
    VelocityX: telemetry.chassis.velocityLS[0]!,
    VelocityY: telemetry.chassis.velocityLS[1]!,
    VelocityZ: telemetry.chassis.velocityLS[2]!,
    AngularVelocityX: telemetry.chassis.angularVelocityLS[0]!,
    AngularVelocityY: telemetry.chassis.angularVelocityLS[1]!,
    AngularVelocityZ: telemetry.chassis.angularVelocityLS[2]!,
    Yaw: 0,
    Pitch: 0,
    Roll: 0,
    NormSuspensionTravelFL: 0,
    NormSuspensionTravelFR: 0,
    NormSuspensionTravelRL: 0,
    NormSuspensionTravelRR: 0,
    TireSlipRatioFL: telemetry.wheels[0]!.slipRatio,
    TireSlipRatioFR: telemetry.wheels[1]!.slipRatio,
    TireSlipRatioRL: telemetry.wheels[2]!.slipRatio,
    TireSlipRatioRR: telemetry.wheels[3]!.slipRatio,
    WheelRotationSpeedFL: telemetry.wheels[0]!.angularVelocity,
    WheelRotationSpeedFR: telemetry.wheels[1]!.angularVelocity,
    WheelRotationSpeedRL: telemetry.wheels[2]!.angularVelocity,
    WheelRotationSpeedRR: telemetry.wheels[3]!.angularVelocity,
    WheelOnRumbleStripFL: 0,
    WheelOnRumbleStripFR: 0,
    WheelOnRumbleStripRL: 0,
    WheelOnRumbleStripRR: 0,
    WheelInPuddleDepthFL: 0,
    WheelInPuddleDepthFR: 0,
    WheelInPuddleDepthRL: 0,
    WheelInPuddleDepthRR: 0,
    SurfaceRumbleFL_2: 0,
    SurfaceRumbleFR_2: 0,
    SurfaceRumbleRL_2: 0,
    SurfaceRumbleRR_2: 0,
    TireSlipCombinedFL_2: 0,
    TireTempFL: telemetry.wheels[0]!.treadTemp[1]!,
    TireTempFR: telemetry.wheels[1]!.treadTemp[1]!,
    TireTempRL: telemetry.wheels[2]!.treadTemp[1]!,
    TireTempRR: telemetry.wheels[3]!.treadTemp[1]!,
    Boost: 0,
    Fuel: telemetry.drivetrain.fuelRemaining,
    DistanceTraveled: (Math.max(1, state.currentLap) - 1 + state.lapProgress) * race.layoutLength,
    BestLap: state.bestLapTime,
    LastLap: state.lastLapTime ?? 0,
    CurrentLap: state.currentLapTime,
    CurrentRaceTime: 0,
    LapNumber: Math.max(1, state.currentLap),
    RacePosition: state.racePos,
    Accel: input255(telemetry.input.accelerator),
    Brake: input255(telemetry.input.brake),
    Clutch: input255(telemetry.input.clutch),
    HandBrake: input255(telemetry.input.handbrake),
    Gear: canonicalGear(telemetry.input.gear),
    Steer: Math.round(clamp(telemetry.input.steering, -1, 1) * 127),
    NormDrivingLine: 0,
    NormAIBrakeDiff: 0,
    TireWearFL: 0,
    TireWearFR: 0,
    TireWearRL: 0,
    TireWearRR: 0,
    SurfaceRumbleFL: 0,
    SurfaceRumbleFR: 0,
    SurfaceRumbleRL: 0,
    SurfaceRumbleRR: 0,
    TireSlipAngleFL: telemetry.wheels[0]!.slipAngle,
    TireSlipAngleFR: telemetry.wheels[1]!.slipAngle,
    TireSlipAngleRL: telemetry.wheels[2]!.slipAngle,
    TireSlipAngleRR: telemetry.wheels[3]!.slipAngle,
    TireCombinedSlipFL: 0,
    TireCombinedSlipFR: 0,
    TireCombinedSlipRL: 0,
    TireCombinedSlipRR: 0,
    SuspensionTravelMFL: 0,
    SuspensionTravelMFR: 0,
    SuspensionTravelMRL: 0,
    SuspensionTravelMRR: 0,
    CarOrdinal: carOrdinal,
    CarClass: 0,
    CarPerformanceIndex: 0,
    DrivetrainType: 0,
    NumCylinders: 0,
    PositionX: telemetry.chassis.posWS[0]!,
    PositionY: telemetry.chassis.posWS[1]!,
    PositionZ: telemetry.chassis.posWS[2]!,
    Speed: telemetry.chassis.overallSpeed,
    Power: telemetry.drivetrain.enginePower,
    Torque: telemetry.drivetrain.engineTorque,
    TrackOrdinal: trackOrdinal,
  };
}
